name: Release and Deploy

run-name: Release and Deploy

on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Release
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    uses: ./.github/workflows/reusable_release.yml
    permissions:
      contents: write
    secrets:
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: release
    steps:
      - run: |
          echo "should-release: ${{ fromJson(needs.release.outputs.should-release) }}"
          echo "prev-version: ${{ needs.release.outputs.prev-version }}"
          echo "version: ${{ needs.release.outputs.version }}"
