name: Release

on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Release
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    uses: ./.github/workflows/reusable_release.yml
    permissions:
      contents: write
    secrets:
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - run: |
          echo "should-release: ${{ fromJson(needs.release.outputs.should-release) }}"
          echo "prev-version: ${{ fromJson(needs.release.outputs.prev-version) }}"
          echo "version: ${{ fromJson(needs.release.outputs.version) }}"
