name: Release

on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Release
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    uses: ./.github/workflows/reusable_release.yml
    permissions:
      contents: write
    secrets:
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
