name: Release it reusable workflow

on:
  workflow_call:
    inputs:
      release-it-args:
        type: string
        description: "Arguments for release-it"
      after-install-command:
        type: string
      after-release-command:
        type: string
      check-if-should-release:
        type: boolean
        default: true
      backmerge:
        type: boolean
        default: true
    secrets:
      gpg-private-key:
      gpg-passphrase:
      checkout-token:
      npm-token:
      release-token:
    outputs:
      should-release:
        value: ${{ jobs.release-it.outputs.should-release }}
      name:
        value: ${{ jobs.release-it.outputs.name }}
      changelog:
        value: ${{ jobs.release-it.outputs.changelog }}
      latest-version:
        value: ${{ jobs.release-it.outputs.latest-version }}
      version:
        value: ${{ jobs.release-it.outputs.version }}

env:
  GIT_AUTHOR_NAME: 41898282+github-actions[bot]@users.noreply.github.com
  GIT_AUTHOR_EMAIL: github-actions[bot]

jobs:
  release-it:
    name: Release it
    runs-on: ubuntu-latest

    outputs:
      should-release: ${{ steps.should-release.outputs.value }}
      name: ${{ steps.release-it.outputs.name }}
      changelog: ${{ steps.release-it.outputs.changelog }}
      latest-version: ${{ steps.release-it.outputs.latest-version }}
      version: ${{ steps.release-it.outputs.version }}

    steps:
      - name: Increase watchers to fix Docker
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.checkout-token || github.token }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 2
          retry_on: error
          command: yarn install --prefer-offline --frozen-lockfile --silent

      - name: Run after install command
        if: inputs.after-install-command
        run: ${{ inputs.after-install-command }}

      - name: Import GPG key
        id: import-gpg
        if: env.GPG_PRIVATE_KEY && env.GPG_PASSPHRASE
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          passphrase: ${{ env.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.gpg-private-key }}
          GPG_PASSPHRASE: ${{ secrets.gpg-passphrase }}

      - name: Check if should release
        id: should-release
        if: inputs.check-if-should-release
        run: |
          if npx should-release-it; then
            echo "value=true" >> $GITHUB_OUTPUT
          else
            echo "value=false" >> $GITHUB_OUTPUT
          fi

      - name: Add npm token
        if: steps.should-release.outputs.value == 'true' && env.NPM_TOKEN
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.npm-token }}

      - name: Release it
        id: release-it
        if: steps.should-release.outputs.value == 'true'
        uses: mathiasvr/command-output@v2.0.0
        with:
          run: npx release-it ${{ inputs.release-it-args }} -VV --ci ${{ (github.ref_name == 'beta' && '--preRelease=beta') || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.release-token || github.token }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name || env.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email || env.GIT_AUTHOR_EMAIL }}

      - name: Release it output
        if: steps.should-release.outputs.value == 'true'
        run: echo "${{ steps.release-it.outputs.stdout }}"

      - name: Run after release command
        if: inputs.after-release-command
        run: ${{ inputs.after-release-command }}

      - name: Perform backmerge from main into beta
        if: github.ref_name == 'main' && inputs.backmerge
        run: |
          git checkout -B main
          git checkout -B beta
          git rebase origin/main
          [[ `git status -s -uno` ]] && git commit -m "chore(release): merge main into beta [skip ci]"
          git push --no-verify origin HEAD:beta
        env:
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name || env.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email || env.GIT_AUTHOR_EMAIL }}
